### PR TITLE
Feat/general base ui

### PR DESCRIPTION
**Pull request by zuhairnaqi**
Worked on #1 @imkaka kindly review the branch and if all OK then merge it so, I can move forward.

### CODE REVIEW

**Comment by zuhairnaqi** [comment]
app
App is looking like this.

**Comment by imkaka** [comment]
Hi @zuhairnaqi great!! 

Can you also add the preview of our app in README? Maybe take a screen shot and add in top?

**Review by imkaka — APPROVED** [review]

**Comment by imkaka** [comment]
LGTM, will merge this after your README commit.

**Comment by zuhairnaqi** [comment]
@imkaka Added preview of app in readme kindly review it.

**Comment by zuhairnaqi** [comment]
@imkaka kindly add label hacktoberfest-accepted on this PR, so it'll count as my hacktoberfest contribution.

**Pull request merged**
