### PR TITLE
Feat/router and ui designs

### PR DESCRIPTION
**Pull request by zuhairnaqi**
Completed issue #2 and #3, Kindly review my PR.
Also added app preview image on readme file

### CODE REVIEW

**Comment by zuhairnaqi** [comment]
Kindly first merge PR #3 then this one.

**Comment by imkaka** [comment]
Hi @zuhairnaqi great work, can you sync it with main once so that it can have relates changes only. 


Also check the preview image in README is giving 404.

And we can keep the project setup steps in README after preview like npm install and start commands for any newbie to get started with this in minutes.

**Comment by zuhairnaqi** [comment]
@imkaka ok

**Comment by zuhairnaqi** [comment]
Hi @imkaka I updated the readme file for getting started for beginners and fix the image issue.
And it is sync with the main.
Kindly review my PR.

**Comment by imkaka** [comment]
@zuhairnaqi Preview images are still giving 400 as you have defined   `.png` in README but file name has `.PNG` maybe you need to rename there or change in README.

**Review by imkaka — APPROVED** [review]

**Comment by imkaka** [comment]
Great work @zuhairnaqi thank you for your contributions. 

I learnt a lot from you. 😇

**Pull request merged**
